services:
  frontend:
    build:
      context: ../client  # Adjust path if necessary
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - mern-network
    depends_on:
      - backend

  backend:
    build:
      context: .   # Ensure this path is correct relative to the location of docker-compose.yml
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
     
      
       # Use .env file for environment variables
       - MONGODB_URI=${MONGODB_URI}
       - KEY=${KEY}
       - EMAIL=${EMAIL}
       - EMAIL_PASSWORD=${EMAIL_PASSWORD}
       - PORT=${PORT}
    networks:
      - mern-network
    volumes:
      - .:/app  # Ensure this path is correct
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongodb:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongodb:



